### ISSUE TITLE
PrimeFaces Native Build fails with POI 2.1.0

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-poi#126]
See: https://github.com/quarkiverse/quarkus-primefaces/actions/runs/11268755147/job/31336077122

```
Finished generating 'quarkus-primefaces-integration-tests-999-SNAPSHOT-runner' in 1m 56s.
Error: Discovered unresolved method during parsing: org.apache.commons.io.input.BoundedInputStream.builder(). This error is reported at image build time because class org.apache.poi.poifs.crypt.cryptoapi.CryptoAPIDecryptor is registered for linking at image build time by command line and command line.
Error encountered while parsing org.apache.poi.poifs.crypt.cryptoapi.CryptoAPIDecryptor.getSummaryEntries(CryptoAPIDecryptor.java:174) 
Parsing context:
   at org.apache.poi.POIDocument.getPropertySet(POIDocument.java:229)
   at org.apache.poi.POIDocument.getPropertySet(POIDocument.java:202)
   at org.apache.poi.POIDocument.readPropertySet(POIDocument.java:175)
   at org.apache.poi.POIDocument.readProperties(POIDocument.java:158)
   at org.apache.poi.POIDocument.readProperties(POIDocument.java:143)
   at org.apache.poi.POIDocument.getDocumentSummaryInformation(POIDocument.java:96)
   at org.apache.poi.POIDocument.writeProperties(POIDocument.java:293)
   at org.apache.poi.hssf.usermodel.HSSFWorkbook.write(HSSFWorkbook.java:1427)
   at org.apache.poi.hssf.usermodel.HSSFWorkbook.write(HSSFWorkbook.java:1410)
   at org.primefaces.component.datatable.export.DataTableExcelExporter.postExport(DataTableExcelExporter.java:80)
   at root method.(Unknown Source)

Error: Discovered unresolved method during parsing: org.apache.commons.io.input.BoundedInputStream.builder(). This error is reported at image build time because class org.apache.poi.poifs.crypt.cryptoapi.CryptoAPIDocumentOutputStream is registered for linking at image build time by command line and command line.
Error encountered while parsing org.apache.poi.poifs.crypt.cryptoapi.CryptoAPIEncryptor.setSummaryEntries(CryptoAPIEncryptor.java:127) 
Parsing context:
   at org.apache.poi.POIDocument.writeProperties(POIDocument.java:310)
   at org.apache.poi.hssf.usermodel.HSSFWorkbook.write(HSSFWorkbook.java:1427)
   at org.apache.poi.hssf.usermodel.HSSFWorkbook.write(HSSFWorkbook.java:1410)
   at org.primefaces.component.datatable.export.DataTableExcelExporter.postExport(DataTableExcelExporter.java:80)
   at root method.(Unknown Source)

Error: Discovered unresolved method during parsing: org.apache.commons.io.input.BoundedInputStream.builder(). This error is reported at image build time because class org.apache.poi.util.IOUtils is registered for linking at image build time by command line and command line.
Error encountered while parsing org.apache.poi.hpsf.PropertySet.<init>(PropertySet.java:188) 
Parsing context:
   at org.apache.poi.hpsf.PropertySetFactory.create(PropertySetFactory.java:106)
   at org.apache.poi.POIDocument.getPropertySet(POIDocument.java:243)
   at org.apache.poi.POIDocument.getPropertySet(POIDocument.java:202)
   at org.apache.poi.POIDocument.readPropertySet(POIDocument.java:175)
   at org.apache.poi.POIDocument.readProperties(POIDocument.java:158)
   at org.apache.poi.POIDocument.readProperties(POIDocument.java:143)
   at org.apache.poi.POIDocument.getDocumentSummaryInformation(POIDocument.java:96)
   at org.apache.poi.POIDocument.writeProperties(POIDocument.java:293)
   at org.apache.poi.hssf.usermodel.HSSFWorkbook.write(HSSFWorkbook.java:1427)
   at org.apache.poi.hssf.usermodel.HSSFWorkbook.write(HSSFWorkbook.java:1410)
   at org.primefaces.component.datatable.export.DataTableExcelExporter.postExport(DataTableExcelExporter.java:80)
   at root method.(Unknown Source)


com.oracle.svm.core.util.UserError$UserException: Unsupported features in 3 methods
Detailed message:
Error: Discovered unresolved method during parsing: org.apache.commons.io.input.BoundedInputStream.builder(). This error is reported at image build time because class org.apache.poi.poifs.crypt.cryptoapi.CryptoAPIDecryptor is registered for linking at image build time by command line and command line.
Error encountered while parsing org.apache.poi.poifs.crypt.cryptoapi.CryptoAPIDecryptor.getSummaryEntries(CryptoAPIDecryptor.java:174) 
Parsing context:
   at org.apache.poi.POIDocument.getPropertySet(POIDocument.java:229)
   at org.apache.poi.POIDocument.getPropertySet(POIDocument.java:202)
   at org.apache.poi.POIDocument.readPropertySet(POIDocument.java:175)
   at org.apache.poi.POIDocument.readProperties(POIDocument.java:158)
   at org.apache.poi.POIDocument.readProperties(POIDocument.java:143)
   at org.apache.poi.POIDocument.getDocumentSummaryInformation(POIDocument.java:96)
   at org.apache.poi.POIDocument.writeProperties(POIDocument.java:293)
   at org.apache.poi.hssf.usermodel.HSSFWorkbook.write(HSSFWorkbook.java:1427)
   at org.apache.poi.hssf.usermodel.HSSFWorkbook.write(HSSFWorkbook.java:1410)
   at org.primefaces.component.datatable.export.DataTableExcelExporter.postExport(DataTableExcelExporter.java:80)
   at root method.(Unknown Source)

Error: Discovered unresolved method during parsing: org.apache.commons.io.input.BoundedInputStream.builder(). This error is reported at image build time because class org.apache.poi.poifs.crypt.cryptoapi.CryptoAPIDocumentOutputStream is registered for linking at image build time by command line and command line.
Error encountered while parsing org.apache.poi.poifs.crypt.cryptoapi.CryptoAPIEncryptor.setSummaryEntries(CryptoAPIEncryptor.java:127) 
Parsing context:
   at org.apache.poi.POIDocument.writeProperties(POIDocument.java:310)
   at org.apache.poi.hssf.usermodel.HSSFWorkbook.write(HSSFWorkbook.java:1427)
   at org.apache.poi.hssf.usermodel.HSSFWorkbook.write(HSSFWorkbook.java:1410)
   at org.primefaces.component.datatable.export.DataTableExcelExporter.postExport(DataTableExcelExporter.java:80)
   at root method.(Unknown Source)

Error: Discovered unresolved method during parsing: org.apache.commons.io.input.BoundedInputStream.builder(). This error is reported at image build time because class org.apache.poi.util.IOUtils is registered for linking at image build time by command line and command line.
Error encountered while parsing org.apache.poi.hpsf.PropertySet.<init>(PropertySet.java:188) 
Parsing context:
   at org.apache.poi.hpsf.PropertySetFactory.create(PropertySetFactory.java:106)
   at org.apache.poi.POIDocument.getPropertySet(POIDocument.java:243)
   at org.apache.poi.POIDocument.getPropertySet(POIDocument.java:202)
   at org.apache.poi.POIDocument.readPropertySet(POIDocument.java:175)
   at org.apache.poi.POIDocument.readProperties(POIDocument.java:158)
   at org.apache.poi.POIDocument.readProperties(POIDocument.java:143)
   at org.apache.poi.POIDocument.getDocumentSummaryInformation(POIDocument.java:96)
   at org.apache.poi.POIDocument.writeProperties(POIDocument.java:293)
   at org.apache.poi.hssf.usermodel.HSSFWorkbook.write(HSSFWorkbook.java:1427)
   at org.apache.poi.hssf.usermodel.HSSFWorkbook.write(HSSFWorkbook.java:1410)
   at org.primefaces.component.datatable.export.DataTableExcelExporter.postExport(DataTableExcelExporter.java:80)
   at root method.(Unknown Source)


	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:248)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:814)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:592)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:539)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:721)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:143)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:98)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 3 methods
Detailed message:
Error: Discovered unresolved method during parsing: org.apache.commons.io.input.BoundedInputStream.builder(). This error is reported at image build time because class org.apache.poi.poifs.crypt.cryptoapi.CryptoAPIDecryptor is registered for linking at image build time by command line and command line.
Error encountered while parsing org.apache.poi.poifs.crypt.cryptoapi.CryptoAPIDecryptor.getSummaryEntries(CryptoAPIDecryptor.java:174) 
Parsing context:
   at org.apache.poi.POIDocument.getPropertySet(POIDocument.java:229)
   at org.apache.poi.POIDocument.getPropertySet(POIDocument.java:202)
   at org.apache.poi.POIDocument.readPropertySet(POIDocument.java:175)
   at org.apache.poi.POIDocument.readProperties(POIDocument.java:158)
   at org.apache.poi.POIDocument.readProperties(POIDocument.java:143)
   at org.apache.poi.POIDocument.getDocumentSummaryInformation(POIDocument.java:96)
   at org.apache.poi.POIDocument.writeProperties(POIDocument.java:293)
   at org.apache.poi.hssf.usermodel.HSSFWorkbook.write(HSSFWorkbook.java:1427)
   at org.apache.poi.hssf.usermodel.HSSFWorkbook.write(HSSFWorkbook.java:1410)
   at org.primefaces.component.datatable.export.DataTableExcelExporter.postExport(DataTableExcelExporter.java:80)
   at root method.(Unknown Source)

Error: Discovered unresolved method during parsing: org.apache.commons.io.input.BoundedInputStream.builder(). This error is reported at image build time because class org.apache.poi.poifs.crypt.cryptoapi.CryptoAPIDocumentOutputStream is registered for linking at image build time by command line and command line.
Error encountered while parsing org.apache.poi.poifs.crypt.cryptoapi.CryptoAPIEncryptor.setSummaryEntries(CryptoAPIEncryptor.java:127) 
Parsing context:
   at org.apache.poi.POIDocument.writeProperties(POIDocument.java:310)
   at org.apache.poi.hssf.usermodel.HSSFWorkbook.write(HSSFWorkbook.java:1427)
   at org.apache.poi.hssf.usermodel.HSSFWorkbook.write(HSSFWorkbook.java:1410)
   at org.primefaces.component.datatable.export.DataTableExcelExporter.postExport(DataTableExcelExporter.java:80)
   at root method.(Unknown Source)

Error: Discovered unresolved method during parsing: org.apache.commons.io.input.BoundedInputStream.builder(). This error is reported at image build time because class org.apache.poi.util.IOUtils is registered for linking at image build time by command line and command line.
Error encountered while parsing org.apache.poi.hpsf.PropertySet.<init>(PropertySet.java:188) 
Parsing context:
   at org.apache.poi.hpsf.PropertySetFactory.create(PropertySetFactory.java:106)
   at org.apache.poi.POIDocument.getPropertySet(POIDocument.java:243)
   at org.apache.poi.POIDocument.getPropertySet(POIDocument.java:202)
   at org.apache.poi.POIDocument.readPropertySet(POIDocument.java:175)
   at org.apache.poi.POIDocument.readProperties(POIDocument.java:158)
   at org.apache.poi.POIDocument.readProperties(POIDocument.java:143)
   at org.apache.poi.POIDocument.getDocumentSummaryInformation(POIDocument.java:96)
   at org.apache.poi.POIDocument.writeProperties(POIDocument.java:293)
   at org.apache.poi.hssf.usermodel.HSSFWorkbook.write(HSSFWorkbook.java:1427)
   at org.apache.poi.hssf.usermodel.HSSFWorkbook.write(HSSFWorkbook.java:1410)
   at org.primefaces.component.datatable.export.DataTableExcelExporter.postExport(DataTableExcelExporter.java:80)
   at root method.(Unknown Source)


	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:[809](https://github.com/quarkiverse/quarkus-primefaces/actions/runs/11268755147/job/31336077122#step:6:810))
```

**Comment by melloware** [comment]
I will investigate this @gastaldi

**Comment by melloware** [comment]
Fixed in PrimeFaces it was a conflicting version.
