### ISSUE TITLE
registerXMLBeansClassesForReflection Error

### ISSUE THREAD

**Issue by aelzo1209** [quarkiverse/quarkus-poi#23]
Hello, I have a small quarkus application that the only thing it does is enable an endpoint in which to obtain an excel file. At first I have used apache POI directly and everything works correctly for me. I wanted to try using quarkus-poi, but it gives me the following error:
Execution failed for task ':quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.poi.deployment.POIProcessor#registerXMLBeansClassesForReflection threw an exception: java.lang.NoSuchMethodError: 'java.util.Collection org.jboss.jandex.IndexView.getAllKnownImplementors(java.lang.Class)'
        at io.quarkiverse.poi.deployment.POIProcessor.registerXMLBeansClassesForReflection(POIProcessor.java:54)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
....

The resource:

@Path("/hello")
public class GreetingResource {

	@Inject
	FicherosService ficherosService;
	
	@Path("/export")
        @GET
        public Response exportAllData() throws IOException {
    	   ByteArrayInputStream stream = ficherosService.exportData();    	
    	   Response.ResponseBuilder response = Response.ok(stream);
    	   response.header(String.valueOf(HttpHeaders.CONTENT_DISPOSITION), "attachment; filename=aplicaciones.xlsx");    	
	   return response.build();
    }
}

The service class:

@ApplicationScoped
public class FicheroServiceImpl implements FicherosService {
	
	@Override
	public ByteArrayInputStream exportData() throws IOException {
		String[] columns = {"Id", "Nombre", "Url"};
		Workbook workbook = new HSSFWorkbook();
		ByteArrayOutputStream stream = new ByteArrayOutputStream();
		Sheet sheet = workbook.createSheet("Lista negra");
		Row row = sheet.createRow(0);
		for(int i=0; i<columns.length; i++) {
			Cell cell = row.createCell(i);
			cell.setCellValue(columns[i]);
		}
		List<Aplicaciones> aplicaciones = Arrays.asList(
				new Aplicaciones(1L, "AAAAAAAAAAAAAAAAAAA", "dd", false),
				new Aplicaciones(2L, "BBBBBBBBBBBBBBBBBBBB", "22", false),
				new Aplicaciones(3L, "CCCCCCCCCC", "", false),
				new Aplicaciones(4L, "DDDDDDDDDDDDD", "", false),
				new Aplicaciones(5L, "EEEEEEEEEEEEEEEEEE", "ff", false),
				new Aplicaciones(6L, "FFFFFFFFFFFFFFFFFFFFF", "", false)
		);
		int initRow = 1;
		for(Aplicaciones app: aplicaciones) {
			row = sheet.createRow(initRow);
			row.createCell(0).setCellValue(app.getId());
			row.createCell(1).setCellValue(app.getName());
			row.createCell(2).setCellValue(app.getUrl());
			initRow++;
		}
		workbook.write(stream);
		workbook.close();
		return new ByteArrayInputStream(stream.toByteArray());
	}
}

And model class called Aplicaciones with its constructors, attributes and its getters and setters.
What am I missing or what am I doing wrong?

**Comment by gastaldi** [comment]
It depends on the Quarkus version you're using. If you're using Quarkus 2.16, you need to use quarkus-poi 1.0.2

**Comment by aelzo1209** [comment]
It seems that was the problem. I started my project from https://code.quarkus.redhat.com/ and the generated gradle.settings was like:

#Gradle properties
quarkusPluginId=io.quarkus
quarkusPluginVersion=2.13.7.Final
quarkusPlatformGroupId=com.redhat.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=2.13.7.Final-redhat-00003

Now y have updated and it works fine.

quarkusPluginId=io.quarkus
quarkusPluginVersion=2.16.3.Final
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=2.16.3.Final

I can run it and build it and everything goes right. The problem comes when i want to generate native image:

gradlew build -Dquarkus.package.type=native
Starting a Gradle Daemon, 1 incompatible and 3 stopped Daemons could not be reused, use --status for details
> Task :quarkusBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:286)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
  Caused by: java.lang.UnsupportedOperationException: Windows AWT integration is not ready in native-image and would result in java.lang.UnsatisfiedLinkError: no awt in java.library.path.
        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep$NativeImageInvokerInfo$Builder.build(NativeImageBuildStep.java:898)
        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:254)
        ... 11 more

**Comment by gastaldi** [comment]
Are you running in macOS M1 by chance?

**Comment by aelzo1209** [comment]
No. Windows 10 Pro. And GraalVM.

**Comment by gastaldi** [comment]
Ah just saw the error message. GraalVM is missing AWT support for Windows and macOS. Unless you build it in a Linux environment that's not going to work

**Comment by gastaldi** [comment]
I'm closing it for now as it's a GraalVM issue
