### ISSUE TITLE
Setting Auto filter leads to "resource 'functionMetadataCetab.txt' not found

### ISSUE THREAD

**Issue by argenstijn** [quarkiverse/quarkus-poi#46]
HI Hello:

When i perform  sheet.setAutoFilter(new CellRangeAddress(0, 0, 0,10)); on my excel it fails with the following in native mode:

"exception": {
        "refId": 1,
        "exceptionType": "java.lang.RuntimeException",
        "message": "resource 'functionMetadataCetab.txt' not found",
        "frames": [
            {
                "class": "org.apache.poi.ss.formula.function.FunctionMetadataReader",
                "method": "readResourceFile",
                "line": 88
            },
            {
                "class": "org.apache.poi.ss.formula.function.FunctionMetadataReader",
                "method": "createRegistryCetab",
                "line": 81
            },
            {
                "class": "org.apache.poi.ss.formula.function.FunctionMetadataRegistry",
                "method": "getInstanceCetab",
                "line": 53
            },
            {
                "class": "org.apache.poi.ss.formula.function.FunctionMetadataRegistry",
                "method": "getFunctionByName",
                "line": 104
            },
            {
                "class": "org.apache.poi.ss.formula.FormulaParser",
                "method": "isValidCellReference",
                "line": 1289
            },
            {
                "class": "org.apache.poi.ss.formula.FormulaParser",
                "method": "parseSimpleRangePart",
                "line": 1047
            },
            {
                "class": "org.apache.poi.ss.formula.FormulaParser",
                "method": "parseRangeable",
                "line": 478
            },
            {
                "class": "org.apache.poi.ss.formula.FormulaParser",
                "method": "parseRangeExpression",
                "line": 327
            },
            {
                "class": "org.apache.poi.ss.formula.FormulaParser",
                "method": "parseSimpleFactor",
                "line": 1556
            },
            {
                "class": "org.apache.poi.ss.formula.FormulaParser",
                "method": "percentFactor",
                "line": 1514
            },
            {
                "class": "org.apache.poi.ss.formula.FormulaParser",
                "method": "powerFactor",
                "line": 1501
            },
            {
                "class": "org.apache.poi.ss.formula.FormulaParser",
                "method": "Term",
                "line": 1875
            },
            {
                "class": "org.apache.poi.ss.formula.FormulaParser",
                "method": "additiveExpression",
                "line": 2002
            },
            {
                "class": "org.apache.poi.ss.formula.FormulaParser",
                "method": "concatExpression",
                "line": 1986
            },
            {
                "class": "org.apache.poi.ss.formula.FormulaParser",
                "method": "comparisonExpression",
                "line": 1943
            },
            {
                "class": "org.apache.poi.ss.formula.FormulaParser",
                "method": "intersectionExpression",
                "line": 1916
            },
            {
                "class": "org.apache.poi.ss.formula.FormulaParser",
                "method": "unionExpression",
                "line": 1897
            },
            {
                "class": "org.apache.poi.ss.formula.FormulaParser",
                "method": "parse",
                "line": 2044
            },
            {
                "class": "org.apache.poi.ss.formula.FormulaParser",
                "method": "parse",
                "line": 175
            },
            {
                "class": "org.apache.poi.xssf.usermodel.XSSFName",
                "method": "setRefersToFormula",
                "line": 200
            },
            {
                "class": "org.apache.poi.xssf.usermodel.XSSFSheet",
                "method": "setAutoFilter",
                "line": 4275
            },
            {
                "class": "org.apache.poi.xssf.usermodel.XSSFSheet",
                "method": "setAutoFilter",
                "line": 78
            

Context:

Quarkus: 2.16.5
Apache Poi: 1.0.3
Java: 17

**Comment by gastaldi** [comment]
I managed to reproduce it in a test case. Here is the full stack trace: 
```java
Caused by: java.lang.RuntimeException: resource 'functionMetadataCetab.txt' not found
	at org.apache.poi.ss.formula.function.FunctionMetadataReader.readResourceFile(FunctionMetadataReader.java:88)
	at org.apache.poi.ss.formula.function.FunctionMetadataReader.createRegistryCetab(FunctionMetadataReader.java:81)
	at org.apache.poi.ss.formula.function.FunctionMetadataRegistry.getInstanceCetab(FunctionMetadataRegistry.java:53)
	at org.apache.poi.ss.formula.function.FunctionMetadataRegistry.getFunctionByName(FunctionMetadataRegistry.java:104)
	at org.apache.poi.ss.formula.FormulaParser.isValidCellReference(FormulaParser.java:1289)
	at org.apache.poi.ss.formula.FormulaParser.parseSimpleRangePart(FormulaParser.java:1047)
	at org.apache.poi.ss.formula.FormulaParser.parseRangeable(FormulaParser.java:478)
	at org.apache.poi.ss.formula.FormulaParser.parseRangeExpression(FormulaParser.java:327)
	at org.apache.poi.ss.formula.FormulaParser.parseSimpleFactor(FormulaParser.java:1556)
	at org.apache.poi.ss.formula.FormulaParser.percentFactor(FormulaParser.java:1514)
	at org.apache.poi.ss.formula.FormulaParser.powerFactor(FormulaParser.java:1501)
	at org.apache.poi.ss.formula.FormulaParser.Term(FormulaParser.java:1875)
	at org.apache.poi.ss.formula.FormulaParser.additiveExpression(FormulaParser.java:2002)
	at org.apache.poi.ss.formula.FormulaParser.concatExpression(FormulaParser.java:1986)
	at org.apache.poi.ss.formula.FormulaParser.comparisonExpression(FormulaParser.java:1943)
	at org.apache.poi.ss.formula.FormulaParser.intersectionExpression(FormulaParser.java:1916)
	at org.apache.poi.ss.formula.FormulaParser.unionExpression(FormulaParser.java:1897)
	at org.apache.poi.ss.formula.FormulaParser.parse(FormulaParser.java:2044)
	at org.apache.poi.ss.formula.FormulaParser.parse(FormulaParser.java:175)
	at org.apache.poi.xssf.usermodel.XSSFName.setRefersToFormula(XSSFName.java:200)
	at org.apache.poi.xssf.usermodel.XSSFSheet.setAutoFilter(XSSFSheet.java:4275)
	at org.apache.poi.xssf.streaming.SXSSFSheet.setAutoFilter(SXSSFSheet.java:1808)
	at io.quarkiverse.poi.it.POIResource.xlxs(POIResource.java:94)
	at io.quarkiverse.poi.it.POIResource_ClientProxy.xlxs(Unknown Source)
	at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	... 17 more
```
