### ISSUE TITLE
Native-Image Schema is missing: org.apache.poi.schemas.ooxml.system.ooxml.shapelayoutelement

### ISSUE THREAD

**Issue by knuspertante** [quarkiverse/quarkus-poi#59]
Hey, 

first, thanks for your amazing work! 

Currently I try to upgrade to quarkus 3 with quarkiverse.tika 2.2 and quarkiverse.poi 2.2. 

Until now I used quarkus 2, quarkiverse.tike 1.X and poi (but not as quarkus extension). Thats why I had to used [native-image tracing agent](https://www.graalvm.org/latest/reference-manual/native-image/metadata/AutomaticMetadataCollection/) to getter native-image configs. Hope this extension will now make this obsolete. 

I process mainly excel files. In JVM mode all my testfiles works with this extension. In native mode unfortunately one file couldn't process and throws this error: 

```sh
Caused by: org.apache.xmlbeans.SchemaTypeLoaderException: XML-BEANS compiled schema: Could not locate compiled schema resource org/apache/poi/schemas/ooxml/system/ooxml/shapelayoutelement.xsb (org.apache.poi.schemas.ooxml.system.ooxml.shapelayoutelement) - code 0
        at org.apache.xmlbeans.impl.schema.XsbReader.<init>(XsbReader.java:63)
        at org.apache.xmlbeans.impl.schema.SchemaTypeSystemImpl.resolveHandle(SchemaTypeSystemImpl.java:931)
        at org.apache.xmlbeans.SchemaComponent$Ref.getComponent(SchemaComponent.java:111)
        at org.apache.xmlbeans.SchemaGlobalElement$Ref.get(SchemaGlobalElement.java:74)
        at org.apache.xmlbeans.impl.schema.SchemaTypeLoaderBase.findElement(SchemaTypeLoaderBase.java:103)
        at org.apache.xmlbeans.impl.schema.SchemaTypeImpl.createElementType(SchemaTypeImpl.java:993)
        at org.apache.xmlbeans.impl.values.XmlObjectBase.create_element_user(XmlObjectBase.java:879)
        at org.apache.xmlbeans.impl.store.Xobj.getUser(Xobj.java:1597)
        at org.apache.xmlbeans.impl.store.Cur.getUser(Cur.java:2571)
        at org.apache.xmlbeans.impl.store.Cur.getObject(Cur.java:2565)
        at org.apache.xmlbeans.impl.store.Cursor._getObject(Cursor.java:814)
        at org.apache.xmlbeans.impl.store.Cursor.syncWrapHelper(Cursor.java:2529)
        at org.apache.xmlbeans.impl.store.Cursor.syncWrap(Cursor.java:2460)
        at org.apache.xmlbeans.impl.store.Cursor.getObject(Cursor.java:2086)
        at org.apache.poi.xssf.usermodel.XSSFVMLDrawing.read(XSSFVMLDrawing.java:155)
        at org.apache.poi.xssf.usermodel.XSSFVMLDrawing.<init>(XSSFVMLDrawing.java:123)
        at org.apache.poi.ooxml.POIXMLFactory.createDocumentPart(POIXMLFactory.java:61)
        at org.apache.poi.ooxml.POIXMLDocumentPart.read(POIXMLDocumentPart.java:661)
        at org.apache.poi.ooxml.POIXMLDocumentPart.read(POIXMLDocumentPart.java:678)
        at org.apache.poi.ooxml.POIXMLDocument.load(POIXMLDocument.java:165)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:260)
        at org.apache.poi.xssf.usermodel.XSSFWorkbookFactory.createWorkbook(XSSFWorkbookFactory.java:118)
        at org.apache.poi.xssf.usermodel.XSSFWorkbookFactory.create(XSSFWorkbookFactory.java:98)
        at org.apache.poi.xssf.usermodel.XSSFWorkbookFactory.create(XSSFWorkbookFactory.java:36)
        at org.apache.poi.ss.usermodel.WorkbookFactory.lambda$create$2(WorkbookFactory.java:224)
        at org.apache.poi.ss.usermodel.WorkbookFactory.wp(WorkbookFactory.java:329)
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:224)
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:185)
        at io.quarkiverse.poi.it.POIResource.specialFile(POIResource.java:123)
        at io.quarkiverse.poi.it.POIResource_ClientProxy.specialFile(Unknown Source)
        at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        ... 17 more
``` 

As described here: https://poi.apache.org/help/faq.html XMLBeans should be compiled and available through poi-ooxml-full jar

> To use the new OOXML file formats, POI requires a jar containing the file format XSDs, as compiled by [XMLBeans](https://xmlbeans.apache.org/). These XSDs, once compiled into Java classes, live in the org.openxmlformats.schemas namespace.

I don't know if this is the right (or the right schema), but when I debug my [test](https://github.com/knuspertante/quarkus-poi/blob/b13beddf3c9277b1c5b885e9f4819567fa6e8487/integration-tests/src/test/java/io/quarkiverse/poi/it/POIResourceTest.java#LL34C1-L37C6) (could be used also as reproducer), the following schemas are available in [POIProcessor#registerXMLBeansClassesForReflection](https://github.com/quarkiverse/quarkus-poi/blob/9f3fae8ceea7c7ead7c1c6de2f201093252144af/deployment/src/main/java/io/quarkiverse/poi/deployment/POIProcessor.java#L51-L56C22)
- com.microsoft.schemas.office.office.impl.CTShapeLayoutImpl
- com.microsoft.schemas.office.office.impl.ShapelayoutDocumentImpl 

Reproduce: 

1. clone https://github.com/knuspertante/quarkus-poi/tree/bug/shapelayoutelement
2. mvn clean verify -Pnative-image

Thanks for your help!

**Comment by gastaldi** [comment]
Thank you for your report. Can you provide a Pull Request with the failing test case? That would help a lot!

**Comment by knuspertante** [comment]
> Thank you for your report. Can you provide a Pull Request with the failing test case? That would help a lot!

Sure, here #60 

What I tried so far: 

add the following to POIProcessor#registerXMLBeansClassesForReflection, cause when I use tracing agent in jvm mode and process this file the following entries are in reflect-config.json

```json
  {
    "name": "com.microsoft.schemas.office.office.impl.CTShapeLayoutImpl",
    "methods": [
      {
        "name": "<init>",
        "parameterTypes": [
          "org.apache.xmlbeans.SchemaType"
        ]
      }
    ]
  },
  {
    "name": "com.microsoft.schemas.vml.impl.CTShapeImpl",
    "methods": [
      {
        "name": "<init>",
        "parameterTypes": [
          "org.apache.xmlbeans.SchemaType"
        ]
      }
    ]
  },
  {
    "name": "com.microsoft.schemas.vml.impl.CTShapetypeImpl",
    "methods": [
      {
        "name": "<init>",
        "parameterTypes": [
          "org.apache.xmlbeans.SchemaType"
        ]
      }
    ]
  }
```

Both extends XmlComplexContentImpl
- com.microsoft.schemas.vml.impl.CTShapeImpl
- com.microsoft.schemas.vml.impl.CTShapetypeImpl

```java
for (ClassInfo implementor : index.getAllKnownSubclasses(XmlComplexContentImpl.class)) {
            reflectiveClass.produce(
                    ReflectiveClassBuildItem.builder(implementor.name().toString()).build());
        }
````
